[docs] Reformat docstrings to be auto-generated
avinashshenoy97/RusticSOM pull request #6
Opened 2022-10-12 19:18 UTC by beyarkay

Hey!

Dunno if you're accepting PRs, but this is a documentation-only change that basically just uses `///` instead of `//` for docstrings, so that the auto-generated documentation on [docs.rs](https://docs.rs/rusticsom/1.1.1/rusticsom/) will actually display all the existing documentation.

2022-10-13 03:26 UTC, avinashshenoy97 requested changes

2022-10-13 03:26 UTC, avinashshenoy97 commented on README.md
> +
Why'd we remove the heading?

2022-10-13 07:00 UTC, beyarkay commented on README.md
> +
Oh I have no idea, I'll add it back

2022-10-13 07:04 UTC, beyarkay commented
I've added the header back. Apart from that, are there any other issues you can see? I'm using this library for a research project and will likely add some features to it in order to do my research, so there will probably be more feature-related PRs in the next few days.

2022-10-15 13:40 UTC, beyarkay commented
Damnit, I didn't mean to push all those changes into this merge. I'll close and reopen in a bit.

2022-10-15 13:40 UTC, closed without merging